application: not-crossword
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: index.html
  upload: (.*\.(html|css|js))
  
- url: /(.*\.(html|css|js|txt))
  static_files: \1
  upload: (.*\.(html|css|js|txt))
  
- url: /words
  script: words.py
